//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int Did { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Dname { get; set; }
        public string Util { get; set; }
        public string ShouSuoYa { get; set; }
        public string ShuZhangYa { get; set; }
        public string Method { get; set; }
        public string Decipher { get; set; }
        public Nullable<System.DateTime> Pro_Time { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
