//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int Uid { get; set; }
        public string Uacount { get; set; }
        public string Upwd { get; set; }
        public string Uname { get; set; }
        public string Usex { get; set; }
        public int Uage { get; set; }
        public string Phone { get; set; }
        public string IdentificationCard { get; set; }
        public Nullable<int> Bid { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
